apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeflow
  namespace: argocd
spec:
  project: kubeflow
  source:
    repoURL: https://github.com/WenshanL/ArgoFlow
    targetRevision: multi-targets
    path: .
    kustomize:
      version: v4.0.5
  destination:
    server: https://172.16.100.12:6443
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
