apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kfserving
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/WenshanL/ArgoFlow
    targetRevision: HEAD
    path: kubeflow/kfserving
    kustomize:
      version: v4.0.5
  destination:
    server: https://172.16.100.12:6443
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
