apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
stringData:
  secretkey: "JoNrbeY9dttjXvNttf9nZpXs/jv53pSiNWn2d2KVHbIUvuZFmBDDHjUbKp6M/Zxr\nMg4nlw4TziQiPMpFtel32r76snA1wNZnbkme32cfCXnNpV4+xpInh3lRvy6DFDw8\nJ5ER8bxEusQzaXgMda0cE0o3ifSOTkxlQCv9fKfPfQs="
