apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
stringData:
  secretkey: "yzmpLJxGmlQFaHkTgUopLRbtsJ1PHS1slXvqi+SEbYIi+mWqJPJILjTgAF02XSvC\ndqSW/jtrRTWJ7qMzKqEu7LyNUMouuxQbreBL/n/F+Q3FrmO6Bz4GmkiVu0/LiC7M\n2NBJtK0YvSHN8+tpru9E9+BOK3v5ngzOMij3Mki6RCk="
